INSERT INTO LION (ID, NAME, TECH) VALUES (NEXT VALUE FOR LION_SEQ, 'Simba', 'Java');
INSERT INTO LION (ID, NAME, TECH) VALUES (NEXT VALUE FOR LION_SEQ, 'Simba', 'Python');
INSERT INTO LION (ID, NAME, TECH) VALUES (NEXT VALUE FOR LION_SEQ, 'ABC', 'Java');
INSERT INTO LION (ID, NAME, TECH) VALUES (NEXT VALUE FOR LION_SEQ, 'ABC', 'C');
